# Generated by Django 3.0.7 on 2020-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200703_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=None, upload_to='product_pictures'),
        ),
    ]
