# Generated by Django 3.0.7 on 2020-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200703_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_pictures'),
        ),
    ]
